env: "grid_maif"

env_args:
  'map_name': 'grid_maif'
  
  'FREE_SPACE': 0
  'OBSTACLE': 1
  
  'default_env_setting': [8, 10]  # [num_agents, map_size]
  
  'reward_fn': 
    'move': -0.075
    'stay_on_goal': 1
    'stay_off_goal': -0.075
    'collision': -0.5
    'reach_goal': 3
    'formation_scale': 0.001  
    'approach': 0.1
  
 
  'action_mapping': 
    0: [0, 0]    # stay
    1: [-1, 0]   # up
    2: [1, 0]    # down
    3: [0, -1]   # left
    4: [0, 1]    # right
  
  
  'obs_radius': 3
  

  'episode_limit': 500
  
  

  'obstacle_density': 0.0


  'use_predefined': true


  'benchmark_path': "src/envs/grid_maif/test_set/ms32_fs9_na10.pth"